# Generated by Django 5.1.1 on 2024-10-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default="default_username", max_length=150, unique=True
            ),
        ),
    ]
