# Generated by Django 5.1.1 on 2024-10-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("rating", models.FloatField(default=0.0)),
                (
                    "restaurant_name",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                ("r_address", models.CharField(max_length=100)),
                ("r_latitude", models.FloatField(blank=True, null=True)),
                ("r_longitude", models.FloatField(blank=True, null=True)),
                (
                    "my_address",
                    models.CharField(default=None, max_length=100, null=True),
                ),
                ("my_latitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "my_longitude",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_name", models.CharField(max_length=100)),
                ("r_desc", models.TextField()),
                ("r_desc_summary", models.TextField()),
                ("phone_number", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("seats", models.CharField(max_length=30)),
                ("parking", models.CharField(max_length=30)),
                ("closed_days", models.CharField(max_length=30)),
                ("classification", models.CharField(max_length=30)),
            ],
        ),
    ]
